### ISSUE TITLE
application folder exists twice

### ISSUE THREAD

**Issue by axelf** [kenjis/codeigniter-composer-installer#15]
Why exists the application directory twice? It's in the root directory and then in `vendor/codeigniter/framework/application`. Do i need this second folder?

**Comment by kenjis** [comment]
Because CodeIgniter's repository layout is like that, and we install CodeIgniter as a Composer package. So we can update CodeIgniter system with `composer update` commnad.

You don't need `vendor/codeigniter/framework/application`. But Composer manages files in `vendor` directory. So it is better you don't touch them.

**Comment by axelf** [comment]
Thank you. Which folder will be updatet by composer? `/application` or  `vendor/codeigniter/framework/application` ?

**Comment by kenjis** [comment]
`vendor/codeigniter/framework`.
`application` in root folder is never changed.

This installer copies `vendor/codeigniter/framework/application` to `application` once, when you install.
After that, if you update (run `composer update`), `vendor/codeigniter/framework` will be updated (if there is new version). But You did not use and will not use `vendor/codeigniter/framework/application` at all.
Your code is only in `application`, not in `vendor/codeigniter/framework/application`.
